In [3]:
import numpy as np

In [12]:
arr = np.array([])

In [10]:
arr.ndim

3

In [11]:
arr.shape

(1, 1, 0)

In [15]:
range1 = np.arange(1,10, 2)

In [18]:
range1

array([1, 3, 5, 7, 9])

In [19]:
arr = np.logspace(1, 3, 3)
arr

array([  10.,  100., 1000.])

In [9]:
arr = np.array([10000000,2,3,4,5])
arr


array([10000000,        2,        3,        4,        5])

In [10]:
arr.dtype

dtype('int32')